    .engine mycomputer

    .include "constants.asm"
    .include "test.mac.asm"
    
    .include "IOSerial.asm"
    
    LD SP,DSTACK
    CALL initialize
    JP testsStart
    
    .include "MINT.asm"
    .include "ram.asm"
    
    .org $4000

testsStart:

    test ":X10;\\0X", 10
    test ":X10; \\{1 :X100; \\} X", 10
    test ":X10; \\{1 :X100; X \\}", 100
    test ":X10; \\{1 :X100; \\} \\1X", 100
    test "2 \\1x! \\1x@", 2
    test "\\{1 2x! \\} \\1x@", 2
    test "\\{1 :A2x!; \\} \\1A \\1x@", 2

    CALL printStr
    .cstr "Done!!\r\n"
    HALT

    ; test "1", 1
    ; test "0", 0
    ; test "10", 10
    ; test "#10", $10
    ; test "#FF", $FF
    ; test "2 3=", 0
    ; test "3 3=", 1
    ; test "2 3<", 1
    ; test "3 3<", 0
    ; test "3 3>", 0
    ; test "4 3>", 1
    ; test "1 2+", 3
    ; test "123 456+", 123+456
    ; test "64 128+", 64+128
    ; test "5 3-", 2
    ; test "1_ 2+",1
    ; test "1_~",0
    ; test "3 5&", 1
    ; test "3 5|", 7
    ; test "1{", 2
    ; test "1}", 0
    ; test "2}", 1
    ; test "1 2 3 ' +", 3
    ; test "2 3*", 6
    ; test "1 2 3+*", 5
    ; call enter
    ;     .cstr "1 3",$22,"+"
    ; expect "1 3 DUP +", 6
    ; test "5 2/'", 2
    ; test "3 5$ -", 2
    ; test "5 2/$ '", 1
    ; test "2 3%++", 7
    ; test "1 2 3\\R''", 2
    ; test "1 2 3\\R+*", 8
    ; test "10 11 12\\D$ '$ '$ '", 4
    ; test "2a!a@",2
    ; test "3x! 1 x@+x! x@", 4
    ; test "3x! 1_ x@+x! x@", 2
    ; test ":X1; X", 1
    ; test ":A100;A", 100
    ; test ":Aa!; 3A a@", 3
    ; test ":Aa!;:Ba@;4AB", 4
    ; test "[]$ '", 0
    ; test "[3]$ '", 1
    ; test "[3]'@", 3
    ; test "[1 2 3]'@", 1
    ; test "[1 2 3]'2+@", 2
    ; test "\\h@[1]''\\h@$-", 2
    ; test "\\h@[1 2 3]''\\h@$-", 6
    ; test "\\[]$ '", 0
    ; test "\\[3]'\\@", 3
    ; test "\\[3]$ '", 1
    ; test "\\[1 2 3]'\\@", 1
    ; test "\\[1 2 3]'1+\\@", 2
    ; test "\\h@\\[1 2 3]''\\h@$-", 3
    ; test "\\h@\\[1]''\\h@$-", 1
    ; test "\\^A",65
    ; test "0 0(1+)", 0
    ; test "0 1(1+)", 1
    ; test "0 2(1+)", 2
    ; test "0 1(0(1+))", 0
    ; test "0 1(1(1+))", 1
    ; test "0 2(1(1+))", 2
    ; test "0 2(2(1+))", 4
    ; test "0 1(\\i@+)", 0
    ; test "0 2(\\i@+)", 1
    ; test "0 3(\\i@+)", 3
    ; test "0 2(2(\\i@ \\i6+@ ++))", 4
    ; test "0t! 10(1 t@+t!) t@",10
    ; test "0\\(100)(200)",200
    ; test "1\\(100)(200)",100
    ; test "0t! 10(\\i@ 4>\\B \\i@ 1 t@+t!) t@",5
    ; test "0t! [1 2 3] $ a! ( a@ \\i@ {+ @ t@+t! ) t@", 6

    CALL enter
    .cstr "`Done!`"
    HALT
    